/**
 * Standard error codes used across the application
 */
export const ERROR_CODES = {
  // Authentication & Authorization
  AUTH: {
    UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
    FORBIDDEN: 'AUTH_FORBIDDEN',
    INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  },

  // Validation
  VALIDATION: {
    FAILED: 'VALIDATION_ERROR',
    INVALID_INPUT: 'VALIDATION_INVALID_INPUT',
    REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  },

  // Resource Management
  RESOURCE: {
    NOT_FOUND: 'RESOURCE_NOT_FOUND',
    ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
    CONFLICT: 'RESOURCE_CONFLICT',
  },

  // Business Logic
  BUSINESS: {
    OPERATION_FAILED: 'BUSINESS_OPERATION_FAILED',
    INVALID_OPERATION: 'BUSINESS_INVALID_OPERATION',
    LIMIT_EXCEEDED: 'BUSINESS_LIMIT_EXCEEDED',
  },

  // System
  SYSTEM: {
    INTERNAL_ERROR: 'INTERNAL_SERVER_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    DATABASE_ERROR: 'DATABASE_ERROR',
  },
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES][keyof typeof ERROR_CODES[keyof typeof ERROR_CODES]];
