export enum JobType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  FREELANCE = 'FREELANCE',
  INTERNSHIP = 'INTERNSHIP',
  CONTRACT = 'CONTRACT',
  TEMPORARY = 'TEMPORARY',
  APPRENTICESHIP = 'APPRENTICESHIP',
  VIRTUAL = 'VIRTUAL',
  REMOTE = 'REMOTE',
  HYBRID = 'HYBRID',
}