events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # Logging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Upstream definitions
    upstream auth_service {
      server auth-user-service:6060;
      keepalive 32;
    }

    upstream users_service {
      server auth-user-service:6060;
      keepalive 32;
    }

    # upstream project_service {
    #   server project-service:3004;
    #   keepalive 32;
    # }

    # include /etc/nginx/conf.d/*.conf; 
    # Nếu để ở đây, auth.conf (chứa location) sẽ nằm thẳng trong http -> LỖI
    
    server {
      listen 80;
      server_name localhost;

      # Health check
      location / {
          return 200 'API Gateway is running!';
      }

      # --- ĐÚNG (Sửa lại vào đây) ---
      # Vì file auth.conf của bạn chỉ chứa 'location', 
      # nên nó phải được nhúng vào trong khối 'server' này.
      include /etc/nginx/conf.d/*.conf; 
    }
}