events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # CORS Configuration - Must be in http block
    include /etc/nginx/cors-map.conf;

    # Logging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Upstream definitions
    upstream auth_service {
      server auth-user-service:6060;
      keepalive 32;
    }

    upstream users_service {
      server auth-user-service:6060;
      keepalive 32;
    }

    upstream job_service {
      server job-service:6061;
      keepalive 32;
    }

    upstream job_bid_service {
      server job-service:6061;
      keepalive 32;
    }

    # upstream project_service {
    #   server project-service:3004;
    #   keepalive 32;
    # }
    
    server {
      listen 80;
      server_name localhost;

      # Health check
      location / {
          return 200 'API Gateway is running!';
      }

      # Include all location blocks from conf.d
      include /etc/nginx/conf.d/*.conf; 
    }
}